stages:
  - publish

variables:
  CHART_PATH: charts
  CHART_NAMES: infra
  OUT_DIR: infrahq

publish elk:
  tags:
    - kubernetes
  image:
    name: alpine/helm:3.14.0
    entrypoint: [""]
  stage: publish
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
  resource_group: charts-itlabs-io
  before_script:
    - apk add aws-cli
    - aws configure set aws_access_key_id "$S3_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$S3_ACCESS_KEY_SECRET"
    - aws configure set default.region "$S3_REGION"
  script:
    - |
      for CHART_NAME in $CHART_NAMES; do
        helm package ./$CHART_PATH/$CHART_NAME -d $OUT_DIR;
        aws s3 --endpoint-url=$S3_ENDPOINT_URL cp ./$OUT_DIR/$CHART_NAME-*.tgz s3://$S3_BUCKET/$OUT_DIR/;
      done
  after_script:
    - aws s3 --endpoint-url=$S3_ENDPOINT_URL cp s3://$S3_BUCKET/index.yaml index.yaml;
    - helm repo index . --merge index.yaml --url https://charts.itlabs.io;
    - aws s3 --endpoint-url=$S3_ENDPOINT_URL cp index.yaml s3://$S3_BUCKET/index.yaml;
